services:
  api-gateway:
    container_name: api-gateway
    image: doyts/watmarker-api-gateway
    build:
      context: .
      dockerfile: ./microservice/api_gateway/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./microservice/api_gateway/.env:/.env

  watermark:
    container_name: watermark-service
    image: doyts/watmarker-watermark
    build:
      context: .
      dockerfile: ./microservice/watermark_service/Dockerfile
    ports:
      - 6000:6000
    volumes:
      - ./microservice/watermark_service/.env:/.env
