services:
  api-gateway:
    container_name: api-gateway
    image: doyts/watmarker-api-gateway
    build:
      context: .
      dockerfile: ./microservice/api_gateway/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./microservice/api_gateway/.env:/.env
    depends_on:
      - watermark

  watermark:
    container_name: watermark-service
    image: doyts/watmarker-watermark
    build:
      context: .
      dockerfile: ./microservice/watermark_service/Dockerfile
    ports:
      - 6000:6000
    volumes:
      - ./microservice/watermark_service/.env:/.env

  web-app:
    container_name: web-app
    image: doyts/watmarker-web-app
    build:
      context: ./microservice/web_app
      dockerfile: prod.Dockerfile
    environment:
      - API_BASE_URL=http://api-gateway:8080
    ports:
      - 3000:80
    depends_on:
      - api-gateway
