services:
  - type: web
    plan: free
    name: api-gateway
    runtime: image
    image:
      url: docker.io/doyts/watmarker-api-gateway:latest

  - type: web
    plan: free
    name: watermark-service
    runtime: image
    image:
      url: docker.io/doyts/watmarker-watermark:latest
