// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.15.8
// source: proto/watermark/watermark.proto

package watermarkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WatermarkService_ApplyWatermark_FullMethodName = "/watermark.WatermarkService/ApplyWatermark"
)

// WatermarkServiceClient is the client API for WatermarkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatermarkServiceClient interface {
	ApplyWatermark(ctx context.Context, in *ApplyWatermarkRequest, opts ...grpc.CallOption) (*ApplyWatermarkResponse, error)
}

type watermarkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatermarkServiceClient(cc grpc.ClientConnInterface) WatermarkServiceClient {
	return &watermarkServiceClient{cc}
}

func (c *watermarkServiceClient) ApplyWatermark(ctx context.Context, in *ApplyWatermarkRequest, opts ...grpc.CallOption) (*ApplyWatermarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyWatermarkResponse)
	err := c.cc.Invoke(ctx, WatermarkService_ApplyWatermark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatermarkServiceServer is the server API for WatermarkService service.
// All implementations must embed UnimplementedWatermarkServiceServer
// for forward compatibility.
type WatermarkServiceServer interface {
	ApplyWatermark(context.Context, *ApplyWatermarkRequest) (*ApplyWatermarkResponse, error)
	mustEmbedUnimplementedWatermarkServiceServer()
}

// UnimplementedWatermarkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatermarkServiceServer struct{}

func (UnimplementedWatermarkServiceServer) ApplyWatermark(context.Context, *ApplyWatermarkRequest) (*ApplyWatermarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyWatermark not implemented")
}
func (UnimplementedWatermarkServiceServer) mustEmbedUnimplementedWatermarkServiceServer() {}
func (UnimplementedWatermarkServiceServer) testEmbeddedByValue()                          {}

// UnsafeWatermarkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatermarkServiceServer will
// result in compilation errors.
type UnsafeWatermarkServiceServer interface {
	mustEmbedUnimplementedWatermarkServiceServer()
}

func RegisterWatermarkServiceServer(s grpc.ServiceRegistrar, srv WatermarkServiceServer) {
	// If the following call pancis, it indicates UnimplementedWatermarkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatermarkService_ServiceDesc, srv)
}

func _WatermarkService_ApplyWatermark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWatermarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatermarkServiceServer).ApplyWatermark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatermarkService_ApplyWatermark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatermarkServiceServer).ApplyWatermark(ctx, req.(*ApplyWatermarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatermarkService_ServiceDesc is the grpc.ServiceDesc for WatermarkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatermarkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watermark.WatermarkService",
	HandlerType: (*WatermarkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyWatermark",
			Handler:    _WatermarkService_ApplyWatermark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/watermark/watermark.proto",
}
