name: Azure CI

on:
  workflow_run:
    workflows: ["Build and Push Microservice Images"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Changed Services Artifact
        uses: actions/download-artifact@v4
        with:
          name: changed-services

      - name: Load Changed Services
        id: load
        run: |
          source changed-services.env
          echo "api_gateway=$api_gateway" >> $GITHUB_OUTPUT
          echo "watermark_service=$watermark_service" >> $GITHUB_OUTPUT
          echo "common_code=$common_code" >> $GITHUB_OUTPUT

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy API Gateway
        if: ${{ steps.load.outputs.api_gateway == 'true' || steps.load.outputs.common_code == 'true' }}
        run: |
          az containerapp update \
            --name api-gateway \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/watmarker-api-gateway:${{ github.sha }}

      - name: Deploy Watermark Service
        if: ${{ steps.load.outputs.watermark_service == 'true' || steps.load.outputs.common_code == 'true' }}
        run: |
          az containerapp update \
            --name watermark \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/watmarker-watermark:${{ github.sha }}
