name: Build and Push Microservice Images

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types: [completed]

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Detect Changed Services
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api_gateway:
              - 'microservice/api_gateway/**'
            watermark_service:
              - 'microservice/watermark_service/**'
            common_code:
              - 'pkg/**'
              - 'proto/**'
              - 'go.mod'
              - 'go.sum'

      - name: Build and Push API Gateway
        if: steps.filter.outputs.api_gateway == 'true' || steps.filter.outputs.common_code == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./microservice/api_gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/watmarker-api-gateway:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/watmarker-api-gateway:${{ github.sha }}

      - name: Build and Push Watermark Service
        if: steps.filter.outputs.watermark_service == 'true' || steps.filter.outputs.common_code == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./microservice/watermark_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/watmarker-watermark:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/watmarker-watermark:${{ github.sha }}
